#pragma once

#include <stdint.h>

// Generated by tools/ml/export_model.py — default heuristic weights until retrained.

static constexpr uint8_t TINYML_FEATURE_COUNT = 16;

static constexpr uint8_t TINYML_WORK_CLASSES = 4;
static constexpr uint8_t TINYML_GESTURE_CLASSES = 4;
static constexpr uint8_t TINYML_SLEEP_CLASSES = 3;

// Work: vacant, active_focus, static_fatigue, env_noise
static const int8_t WORK_WEIGHTS[TINYML_WORK_CLASSES * TINYML_FEATURE_COUNT] = {
    -8, -6, -4, -2, -10, 0, -3, -3, -2, -4, -2, -12, -6, -4, -2, -3,
    6, 8, 4, 6, 8, 2, 5, 5, 4, 6, 4, 10, 6, 8, 4, 5,
    4, -10, 2, -8, 6, -2, 3, 4, 3, -6, 2, 8, 2, 6, -4, 3,
    -4, 4, 10, 8, -2, 6, 2, 2, 1, 2, 6, -4, 8, 4, 6, 2,
};
static const int8_t WORK_BIAS[TINYML_WORK_CLASSES] = {-20, 10, -5, -8};

// Gesture: none, next, prev, hover
static const int8_t GESTURE_WEIGHTS[TINYML_GESTURE_CLASSES * TINYML_FEATURE_COUNT] = {
    -2, -2, -2, 0, -4, 0, -2, -2, -1, 0, 0, -4, -2, -2, 0, -1,
    2, 4, 8, 2, 6, 10, 6, 4, 3, 2, 2, 4, 6, 4, 2, 3,
    2, 4, 6, 2, 6, -10, 4, 3, 2, 2, 2, 4, 4, 3, 2, 2,
    -2, -6, 2, -4, 8, -2, 5, 5, 4, 4, 2, 6, 2, -8, -6, 4,
};
static const int8_t GESTURE_BIAS[TINYML_GESTURE_CLASSES] = {0, -8, -8, -6};

// Sleep: absent, breathing_stable, restless
static const int8_t SLEEP_WEIGHTS[TINYML_SLEEP_CLASSES * TINYML_FEATURE_COUNT] = {
    -6, -8, -4, -2, -4, 0, -3, -3, -2, -6, -2, -10, -4, -4, -2, -3,
    6, 6, 2, 4, 4, 0, 4, 6, 4, 8, 4, 8, 2, 6, 2, 5,
    4, -4, 8, 10, 2, 4, 2, 2, 2, -4, 6, 4, 8, 8, 4, 2,
};
static const int8_t SLEEP_BIAS[TINYML_SLEEP_CLASSES] = {-15, 5, -5};

static constexpr char TINYML_MODEL_VERSION[] = "0.1.0-heuristic";
